version: '3.1'
services:
  api:
    build:
      # context: .
      dockerfile: ./dockerfile
    volumes:
      # - ./:/app
      # - /app/vendor
    ports:
      - "8000:8000"
    environment:
      # - PORT=9000
    command: "npm run start"
